name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
          directory: back-end/
          file_name: .env
          fail_on_empty: true
        
        - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d